/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.epam.vtbbulpm.nci.avro.model;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Type implements org.apache.avro.generic.GenericEnumSymbol<Type> {
  CREATE, UPDATE, DELETE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Type\",\"namespace\":\"com.epam.vtbbulpm.nci.avro.model\",\"symbols\":[\"CREATE\",\"UPDATE\",\"DELETE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
